// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// NBfactor
SEXP NBfactor(SEXP Ys, int ntopic, int Ndrawn, int Nburnn);
RcppExport SEXP NBfactor_NBfactor(SEXP YsSEXP, SEXP ntopicSEXP, SEXP NdrawnSEXP, SEXP NburnnSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    SEXP Ys = Rcpp::as<SEXP >(YsSEXP);
    int ntopic = Rcpp::as<int >(ntopicSEXP);
    int Ndrawn = Rcpp::as<int >(NdrawnSEXP);
    int Nburnn = Rcpp::as<int >(NburnnSEXP);
    SEXP __result = NBfactor(Ys, ntopic, Ndrawn, Nburnn);
    return Rcpp::wrap(__result);
END_RCPP
}
